title: Topic Lost or Found? - Measuring Topic Fidelity in Reddit TL;DR Summaries
description: Evaluating how well Reddit TL;DR summaries preserve the topics of original posts using BERTopic and LDA.
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-cayman
