title: Topic Lost or Found? - Measuring Topic Fidelity in Reddit TL;DR Summaries
description: Measuring how well Reddit TL;DR summaries preserve the main topic of the original post using LDA and BERTopic.
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal
